Update requirements.txt
streamlit giving this error:

ERROR: Cannot install seaborn==0.11.1 and seaborn==0.12.1 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested seaborn==0.11.1
    The user requested seaborn==0.12.1
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict